# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/bravo/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/htc/bravo/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for bravo
PRODUCT_COPY_FILES += \
    vendor/htc/bravo/proprietary/akmd:system/bin/akmd \
    vendor/htc/bravo/proprietary/parse_radio_log:system/bin/parse_radio_log \
    vendor/htc/bravo/proprietary/AudioBTID.csv:system/etc/AudioBTID.csv \
    vendor/htc/bravo/proprietary/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/htc/bravo/proprietary/default.acdb:system/etc/firmware/default.acdb \
    vendor/htc/bravo/proprietary/default_france.acdb:system/etc/firmware/default_france.acdb \
    vendor/htc/bravo/proprietary/default_nel.acdb:system/etc/firmware/default_nel.acdb \
    vendor/htc/bravo/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/bravo/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/bravo/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/bravo/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/bravo/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/bravo/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/bravo/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/bravo/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/bravo/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/bravo/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/bravo/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/bravo/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/htc/bravo/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/bravo/proprietary/app/Camera.apk:system/app/Camera.apk \
    vendor/htc/bravo/proprietary/app/ChromeBookmarksSyncAdapter.apk:system/app/ChromeBookmarksSyncAdapter.apk \
    vendor/htc/bravo/proprietary/app/Gallery2.apk:system/app/Gallery2.apk \
    vendor/htc/bravo/proprietary/app/GenieWidget.apk:system/app/GenieWidget.apk \
    vendor/htc/bravo/proprietary/app/GoogleBackupTransport.apk:system/app/GoogleBackupTransport.apk \
    vendor/htc/bravo/proprietary/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/htc/bravo/proprietary/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/htc/bravo/proprietary/app/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/htc/bravo/proprietary/app/GoogleLoginService.apk:system/app/GoogleLoginService.apk \
    vendor/htc/bravo/proprietary/app/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/htc/bravo/proprietary/app/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/htc/bravo/proprietary/app/MarketUpdater.apk:system/app/MarketUpdater.apk \
    vendor/htc/bravo/proprietary/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/htc/bravo/proprietary/app/Music.apk:system/app/Music.apk \
    vendor/htc/bravo/proprietary/app/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/htc/bravo/proprietary/app/Phonesky.apk:system/app/Phonesky.apk \
    vendor/htc/bravo/proprietary/app/Talk.apk:system/app/Talk.apk \
    vendor/htc/bravo/proprietary/app/VoiceSearch.apk:system/app/VoiceSearch.apk \
    vendor/htc/bravo/proprietary/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/htc/bravo/proprietary/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/htc/bravo/proprietary/etc/permissions/com.google.android.widevine.software.drm.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/htc/bravo/proprietary/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/htc/bravo/proprietary/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/htc/bravo/proprietary/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/htc/bravo/proprietary/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/htc/bravo/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/htc/bravo/proprietary/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
    vendor/htc/bravo/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/htc/bravo/proprietary/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
    vendor/htc/bravo/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
    vendor/htc/bravo/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/htc/bravo/proprietary/lib/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/htc/bravo/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/bravo/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/htc/bravo/proprietary/lib/libpicowrapper.so:system/lib/libpicowrapper.so \
    vendor/htc/bravo/proprietary/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/htc/bravo/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
    vendor/htc/bravo/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/htc/bravo/proprietary/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    vendor/htc/bravo/proprietary/lib/libvideochat_stabilize.so:system/lib/libvideochat_stabilize.so \
    vendor/htc/bravo/proprietary/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
    vendor/htc/bravo/proprietary/lib/hw/camera.qsd8k.so:system/lib/camera.qsd8k.so \
    vendor/htc/bravo/proprietary/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/htc/bravo/proprietary/lib/egl/libGLES_android.so:system/lib/libGLES_android.so 





#    vendor/htc/bravo/proprietary/libOmxVdec.so:system/lib/libOmxVdec.so



#PRODUCT_COPY_FILES := \
#    vendor/htc/bravo/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for bravo
#PRODUCT_COPY_FILES += \
##    vendor/htc/bravo/proprietary/akmd:system/bin/akmd \
##    vendor/htc/bravo/proprietary/parse_radio_log:system/bin/parse_radio_log \
#    vendor/htc/bravo/proprietary/AudioBTID.csv:system/etc/AudioBTID.csv \
#    vendor/htc/bravo/proprietary/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
#    vendor/htc/bravo/proprietary/default.acdb:system/etc/firmware/default.acdb \
#    vendor/htc/bravo/proprietary/default_france.acdb:system/etc/firmware/default_france.acdb \
#    vendor/htc/bravo/proprietary/default_nel.acdb:system/etc/firmware/default_nel.acdb \
##    vendor/htc/bravo/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
#    vendor/htc/bravo/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
#   vendor/htc/bravo/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
#    vendor/htc/bravo/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
#    vendor/htc/bravo/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
#    vendor/htc/bravo/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
#    vendor/htc/bravo/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
#    vendor/htc/bravo/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
#    vendor/htc/bravo/proprietary/libgsl.so:system/lib/libgsl.so \
#    vendor/htc/bravo/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
#    vendor/htc/bravo/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
#    vendor/htc/bravo/proprietary/libcamera.so:system/lib/libcamera.so \
#    vendor/htc/bravo/proprietary/liboemcamera.so:system/lib/liboemcamera.so 
#    vendor/htc/bravo/proprietary/libOmxVdec.so:system/lib/libOmxVdec.so
